app/urls.py
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm
from django.contrib.auth import views as auth_views
from .views import CustomPasswordResetConfirmView
from django.urls import path
from .views import orders

urlpatterns = [
    path('', views.ProductView.as_view(), name="home"),
    path('product-detail/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),

    path('add-to-cart/', views.add_to_cart, name='add-to-cart'),
    path('cart/', views.show_cart, name='showcart'),
    
    path('pluscart/',views.plus_cart),
    path('minuscart/',views.minus_cart),
    path('removecart/',views.remove_cart),
    
    path('buy/', views.buy_now, name='buy-now'),
    path('profile/', views.ProfileView.as_view(),name='profile'),
    path('address/', views.address, name='address'),
    path('orders/', views.orders, name='orders'),

    path('mobile/', views.mobile, name='mobile'),
    path('laptop/', views.laptop, name='laptop'),
    path('topwear/', views.topwear, name='topwear'),
    path('bottomwear/', views.bottomwear, name='bottomwear'),
    path('mobile/<slug:data>', views.mobile, name='mobiledata'),
    path('laptop/<slug:data>', views.laptop, name='laptopdata'),
    path('topwear/<slug:data>', views.topwear, name='topweardata'),
    path('bottomwear/<slug:data>', views.bottomwear, name='bottomweardata'),
    
    path('checkout/', views.checkout, name='checkout'),
    path('paymentdone/', views.payment_done, name='paymentdone'),

    path('accounts/login/', auth_views.LoginView.as_view(template_name='app/login.html', authentication_form=LoginForm),name='login'),
    
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('passwordchange/', auth_views.PasswordChangeView.as_view(template_name='app/passwordchange.html', form_class=MyPasswordChangeForm, success_url='/passwordchangedone/'), name='passwordchange'),
    path('passwordchangedone/', auth_views.PasswordChangeDoneView.as_view(template_name='app/passwordchangedone.html'),name='passwordchangedone'),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',form_class=MyPasswordResetForm), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name='password_reset_complete'),
 
    
    path('registration/', views.CustomerRegistrationView.as_view(), name="customerregistration"),
    
    # Şifre sıfırlama işlemleri için URL'ler
    # path('password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html'), name='password_reset'),
    # path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name='password_reset_done'),
    # path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name='password_reset_complete'),

     # Şifre sıfırlama onay sayfası
    path('password-reset-confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shoppinglyx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth import password_validation
from .models import Customer

class CustomerRegistrationForm(UserCreationForm): 
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput(attrs={'class': 'form-control'})) 
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))

class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']
    labels = {'email': 'Email'}
    widgets = {'username': forms.TextInput(attrs={'class': 'form-control'})}



class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control'}))


class MyPasswordChangeForm (PasswordChangeForm): 
    old_password = forms.CharField(label=_("Old Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True, 'class': 'form-control'}))
    new_password1 = forms.CharField(label=_("New Password"), strip=False, widget=forms.PasswordInput(attrs= {'autocomplete': 'new-password', 'class': 'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"), strip=False, widget=forms.PasswordInput(attrs= {'autocomplete': 'new-password', 'class': 'form-control'}))



class MyPasswordResetForm (PasswordResetForm):
    email=forms.EmailField(label=_("Email"), max_length=254, widget=forms.EmailInput(attrs={'autocomplete': 'email', 'class':'form-control'}))


class MySetPasswordForm(SetPasswordForm): 
    new_password1 = forms.CharField(label=("New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'new-password','class': 'form-control'}), help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label=_("Confirm New Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}))


class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'locality', 'city', 'state', 'zipcode'] 
        widgets = {'name': forms.TextInput(attrs={'class':'form-control' }), 'locality': forms.TextInput(attrs= {'class': 'form-control'}), 'city': forms.TextInput(attrs={'class': 'form-control'}),
        'state': forms.Select(attrs = { 'class': 'form-control'}), 
        'zipcode': forms. NumberInput (attrs={'class': 'form-control'})}




app/templates/app/addtocart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h1 class="text-center mb-5">Shopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3> 
    {% for cart in carts %}
    <hr> 
    <div class="row">
     <div class="col-sm-3 text-center align-self-center"><img src="{{cart.product.product_image.url}}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
     <div class="col-sm-9">
      <div>
       <h5>{{cart.product.title}}</h5>
       <p class="mb-2 text-muted small">{{cart.product.description}}</p>
       <div class="my-3">
        <label for="quantity">Quantity:</label>
        <a class="minus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">{{cart.quantity}}</span>
        <a class="plus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-plus-square fa-lg"></i></a>
       </div> 
       <div class="d-flex justify-content-between">
        <a href="#" class="btn btn-sm btn-secondary mr-3 remove-cart" pid="{{cart.product.id}}">Remove item </a>
        <p class="mb-0"><span><strong>{{cart.product.discounted_price}} TL</strong></span></p>
       </div>
      </div>
     </div>
    </div>
    {% endfor %}
   </div>
   </div>
  </div>

  <div class="col-sm-4">
   <div class="card">
    <div class="card-body">
      <h3>The Total Amount of</h3>
      <ul class="list-group">
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount<span><span id="amount"> {{amount}}</span> TL</span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>70.00 TL</span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total</strong> <small>(including VAT)</small>
         </div>
         <span><strong><strong id="totalamount">{{totalamount}}</strong> TL</strong></span>
       </li>
      </ul>
      <div class="d-grid"><a href="{% url 'checkout' %}" class="btn btn-primary">Place Order</a></div>
    </div>
   </div>
  </div>
  
 </div>
</div>
<div class="container">
 <div class="row">
  <div class="col-sm-8">
   <div class="card">
    <div class="card-body">
      <h5 class="mb-4">We accept</h5>
      <img src="{% static 'app/images/payment.png' %}" alt="" class="img-fluid">
    </div>
  </div>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/base.html
<!doctype html>
{% load static %}
<html lang="en"> 
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css' %}">

    <!--FontAwesome CSS-->
    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">


    <title>ShopVora | {% block title %} {% endblock title %} </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container">
       <a class="navbar-brand" href="/">ShopVora</a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="/">Home</a>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="electronicsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Electronics
             </a>
             <ul class="dropdown-menu" aria-labelledby="electronicsDropdown">
               <li><a class="dropdown-item" href="{% url 'mobile' %}">Mobile</a></li>
               <li><a class="dropdown-item" href="{% url 'laptop' %}">Laptop</a></li>
             </ul>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="fashionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Fashion
             </a>
             <ul class="dropdown-menu" aria-labelledby="fashionDropdown">
               <li><a class="dropdown-item" href="{% url 'topwear' %}">Top Wear</a></li>
               <li><a class="dropdown-item" href="{% url 'bottomwear' %}">Bottom Wear</a></li>
             </ul>
           </li>
         </ul>
         <form class="d-flex">
           <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
         </form>
         <div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            {% if request.user.is_authenticated %}
           <li class="nav-item dropdown mx-2">
              <a class="nav-link dropdown-toggle text-white" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{request.user.username|capfirst}}
              </a>
              <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'orders' %}">Orders</a></li>
                <li><a class="dropdown-item" href="{% url 'passwordchange' %}">Change Password</a></li>
                <form id="logout-form" method="post" action="{% url 'logout' %}" style="display: none;">
                  {% csrf_token %}
              </form>
              
              <li><a href="#" onclick="document.getElementById('logout-form').submit();" class="dropdown-item">Logout</a></li>
              
              </ul>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'showcart' %}" class="nav-link text-white"><span class="badge bg-danger">{{totalitem}}</span> Cart </a>
            </li>
            {% else %}
            <li class="nav-item mx-2">
             <a href="{% url 'login' %}" class="nav-link text-white">Login</a>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'customerregistration' %}" class="nav-link text-white">Registration</a>
            </li>
            {% endif %}
          </ul>
         </div>
       </div>
     </div>
    </nav>
    {% block banner_slider %} {% endblock banner_slider %}
    {% block livesale %} {% endblock livesale %}
    {% block main-content %} {% endblock main-content %}
    {% block payment-gateway %} {% endblock payment-gateway %}

    <!-- Start Footer -->
    <footer class="container-fluid bg-dark text-center p-2 mt-5">
        <small class="text-white">Copyright &copy; 2025 || Re-edited by NuranFerhan || </small>
        <img src="{% static 'app/images/payment.png' %}" alt="" srcset="" class="img-fluid" height="2px">
    </footer> <!-- End Footer -->

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'app/js/all.min.js' %}"></script>
    <script src="{% static 'app/js/myscript.js' %}"></script>
  </body>
</html>

app/templates/app/bottomwear.html
{% extends 'app/base.html' %} 
{% load static %}
{% block title %}Bottom Wear{% endblock title %}
{% block main-content %}
<div class="container my-5">
    <div class="row">   
        <div class="col-sm-3">
            <div class="list-group">
                <a href="{% url 'bottomwear' %}" class="list-group-item list-group-item-action" aria-current="true">All Bottom Wear</a> 
                <a href="{% url 'bottomweardata' 'Spykar' %}" class="list-group-item list-group-item-action" aria-current="true">Spykar</a>
                <a href="{% url 'bottomweardata' 'Lee' %}" class="list-group-item list-group-item-action" aria-current="true">Lee</a>
                <a href="{% url 'bottomweardata' 'below' %}" class="list-group-item list-group-item-action" aria-current="true">Below 550</a>  
                <a href="{% url 'bottomweardata' 'above' %}" class="list-group-item list-group-item-action" aria-current="true">Above 550</a>  
            </div> 
        </div>
        <div class="col-sm-8">
            <div class="row">
                {% for product in bottomwears %}
                <div class="col-sm-4 text-center mb-4">
                    <a href="{% url 'product-detail' product.id %}" class="btn">
                        <div class="item">
                        <img src="{{product.product_image.url}}" alt="" height="300" class="">
                        <div class="fw-bold">{{product.title}}</div>
                        <div class="fw-bold">{{product.discounted_price}} TL <small class="fw-light text-decoration-line-through">{{product.selling_price}}</small></div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}





                

app/templates/app/buynow.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
Product Buy Now
{% endblock main-content %}

app/templates/app/customerregistration.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Customer Registration{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Customer Registration</h3>
   <hr>

   <form action="" method="post" novalidate class="shadow p-5">
   {% if messages %}
      {% for message in messages %}
         <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
      {% endfor %}
   {% endif %}

      {% csrf_token %}
      
      <!-- Username Field -->
      <div class="form-group mb-3">
         <label class="form-label">{{ form.username.label_tag }}</label>
         <input type="{{ form.username.field.widget.input_type }}" name="{{ form.username.name }}" class="form-control" placeholder="{{ form.username.label }}" required>
         <small class="text-danger">{{ form.username.errors|striptags }}</small>
      </div>

      <!-- Email Field -->
      <div class="form-group mb-3">
         <label class="form-label">{{ form.email.label_tag }}</label>
         <input type="{{ form.email.field.widget.input_type }}" name="{{ form.email.name }}" class="form-control" placeholder="{{ form.email.label }}" required>
         <small class="text-danger">{{ form.email.errors|striptags }}</small>
      </div>

      <!-- Password Field -->
      <div class="form-group mb-3">
         <label class="form-label">{{ form.password1.label_tag }}</label>
         <input type="{{ form.password1.field.widget.input_type }}" name="{{ form.password1.name }}" class="form-control" placeholder="{{ form.password1.label }}" required>
         <small class="text-danger">{{ form.password1.errors|striptags }}</small>
      </div>

      <!-- Confirm Password Field -->
      <div class="form-group mb-3">
         <label class="form-label">{{ form.password2.label_tag }}</label>
         <input type="{{ form.password2.field.widget.input_type }}" name="{{ form.password2.name }}" class="form-control" placeholder="{{ form.password2.label }}" required>
         <small class="text-danger">{{ form.password2.errors|striptags }}</small>
      </div>
      
      <input type="submit" value="Submit" class="btn btn-primary">
      <br>
      
      <div class="text-center text-primary fw-bold">
         <small>Existing User? <a href="{% url 'login' %}" class="text-danger">Login Now</a></small>
      </div>
      
      {% if form.non_field_errors %}
         {% for error in form.non_field_errors %}
            <p class="alert alert-danger my-3">{{ error }}</p> 
         {% endfor %}
      {% endif %}
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/emptycart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Empty Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
    <div class="row">
    <h3 class="text-center">You have no Product in Your Cart</h3>
    <div class="text-center">
    <img src="{% static 'app/images/emptycart.png' %}" alt="" class="img-fluid img-thumbnail w-25">
</div>
</div>
</div>
{% endblock main-content %}

app/templates/app/laptop.html
{% extends 'app/base.html' %} 
{% load static %}
{% block title %}Laptop{% endblock title %}
{% block main-content %}
<div class="container my-5">
    <div class="row">   
        <div class="col-sm-3">
            <div class="list-group">
                <a href="{% url 'laptop' %}" class="list-group-item list-group-item-action" aria-current="true">All Laptop</a> 
                <a href="{% url 'laptopdata' 'Apple' %}" class="list-group-item list-group-item-action" aria-current="true">Apple</a>
                <a href="{% url 'laptopdata' 'Lenovo' %}" class="list-group-item list-group-item-action" aria-current="true">Lenovo</a>
                <a href="{% url 'laptopdata' 'MSI' %}" class="list-group-item list-group-item-action" aria-current="true">MSI</a>
                <a href="{% url 'laptopdata' 'HP' %}" class="list-group-item list-group-item-action" aria-current="true">HP</a>
                <a href="{% url 'laptopdata' 'Casper' %}" class="list-group-item list-group-item-action" aria-current="true">Casper</a>
                <a href="{% url 'laptopdata' 'below' %}" class="list-group-item list-group-item-action" aria-current="true">Below 30000</a>  
                <a href="{% url 'laptopdata' 'above' %}" class="list-group-item list-group-item-action" aria-current="true">Above 30000</a>  
            </div> 
        </div>
        <div class="col-sm-8">
            <div class="row">
                {% for product in laptops %}
                <div class="col-sm-4 text-center mb-4">
                    <a href="{% url 'product-detail' product.id %}" class="btn">
                        <div class="item">
                        <img src="{{product.product_image.url}}" alt="" height="300" class="">
                        <div class="fw-bold">{{product.title}}</div>
                        <div class="fw-bold">{{product.discounted_price}} TL <small class="fw-light text-decoration-line-through">{{product.selling_price}}</small></div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}





                

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Login</h3>
   <hr> 
   <form action="" method="post" novalidate class="shadow p-5">
    {% csrf_token %}
    {% for fm in form %}
    <div class="form-group">
    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small> <br>
    </div>
    {% endfor %}
    <small><a href="{% url 'password_reset' %}">Forgot Password ?</a></small> <br>
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
    <div class="text-center">
        <small class="fw-bold text-primary">New to ShopVora?  
            <a href="{% url 'customerregistration' %}" class="text-danger">Create an Account</a>
        </small>
    </div>    
    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}

    </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/mobile.html
{% extends 'app/base.html' %} 
{% load static %}
{% block title %}Mobile{% endblock title %}
{% block main-content %}
<div class="container my-5">
    <div class="row">   
        <div class="col-sm-3">
            <div class="list-group">
                <a href="{% url 'mobile' %}" class="list-group-item list-group-item-action" aria-current="true">All Mobile</a> 
                <a href="{% url 'mobiledata' 'Apple' %}" class="list-group-item list-group-item-action" aria-current="true">Apple</a>
                <a href="{% url 'mobiledata' 'Xiaomi' %}" class="list-group-item list-group-item-action" aria-current="true">Xiaomi</a>
                <a href="{% url 'mobiledata' 'Samsung' %}" class="list-group-item list-group-item-action" aria-current="true">Samsung</a>
                <a href="{% url 'mobiledata' 'below' %}" class="list-group-item list-group-item-action" aria-current="true">Below 15000</a>  
                <a href="{% url 'mobiledata' 'above' %}" class="list-group-item list-group-item-action" aria-current="true">Above 15000</a>  
            </div> 
        </div>
        <div class="col-sm-8">
            <div class="row">
                {% for product in mobiles %}
                <div class="col-sm-4 text-center mb-4">
                    <a href="{% url 'product-detail' product.id %}" class="btn">
                        <div class="item">
                        <img src="{{product.product_image.url}}" alt="" height="300" class="">
                        <div class="fw-bold">{{product.title}}</div>
                        <div class="fw-bold">{{product.discounted_price}} TL <small class="fw-light text-decoration-line-through">{{product.selling_price}}</small></div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock main-content %}





                

app/templates/app/password_reset_complete.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %} Password Reset Complete {% endblock title %}
{% block main-content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3"> 
        <h4>Reset Password Completed!</h4>
        <div><iframe src="https://giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
</div>
</div> 
</div>
{% endblock main-content %}

app/templates/app/password_reset_confirm.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Password Reset Confirm{% endblock title %} 

{% block main-content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Password Reset Confirm</h3>
            <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_new_password1">New Password</label>
                    <input type="password" name="new_password1" id="id_new_password1" class="form-control">
                </div>

                <div class="form-group mt-3">
                    <label for="id_new_password2">Confirm New Password</label>
                    <input type="password" name="new_password2" id="id_new_password2" class="form-control">
                </div>

                <input type="submit" class="btn btn-primary mt-3" value="Submit">
                
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{ error }}</p> 
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock main-content %}